### PR TITLE
[WIP] Replace scss-parser with gonzales-pe

### LINKED ISSUE #18: Problem parsing varargs
Hey, 
as mentioned in #15 varargs in the SCSS lead to a crash.  Since scss-parser isn't that well maintained, maybe gonzales-pe would be a good replacement.

At the moment I'm checking if it is an easy swap and would give it a try, what are your thoughts on that?

### PR DESCRIPTION
**Pull request by phlmn**
Hey, 

I've replaced scss-parser with gonzales-pe to increase compatibility with certain SCSS features, most likely varargs. This fixes #18. Two tests are not running yet, maybe you've an idea for that.

I also added an editorconfig file.

Cheers,
Philipp

### CODE REVIEW

**Comment by jgranstrom** [comment]
@phlmn thank you, I also noticed the varargs issues, sass has a pretty a huge set of features to cover. Unfortunately I have been knee deep in all kinds of things the last weeks so haven't had time to look into it. Will check this alternative parser out tonight and see if we can iron out the remaining issues for a new release.

**Comment by bencergazda** [comment]
I just had some time today to test the `gonzales-pe`-version, this also fixes my [issue](https://github.com/salesforce-ux/scss-parser/issues/19) with [scss-parser](https://github.com/salesforce-ux/scss-parser). Finally I could import my whole module tree for `sass-extract`.

Thank you @jgranstrom for putting the plugin together, and thanks for @phlmn for creating the `gonzales-pe` version of it. Hope it will be included to the plugin. :-)

**Comment by jgranstrom** [comment]
@phlmn @bencergazda this and more has been included in the latest [2.0.0 release](https://github.com/jgranstrom/sass-extract/releases/tag/v2.0.0). Thank you for your work with the parser!

**Comment by phlmn** [comment]
@jgranstrom Awesome! 😊 Still has problems with Bootstrap 4.0.0-beta.2 but that's probably a syntax error in their code...

**Pull request merged**
